### ISSUE TITLE
BIDS App structure

### ISSUE THREAD

**Issue by effigies** [nipreps/fmripost-aroma#1]
fmripost-aroma should be a BIDS app of the form:

```
fmripost-aroma <bids-dir> <out-dir> participant -d <fmriprep-dir> [OPTIONS]
```

The reason for taking the fmriprep directory as a separate derivative input is to permit the utility to retrieve some data from the raw dataset instead of relying entirely on the fmriprep derivatives. This will become necessary when fMRIPrep supports a minimal mode where only transforms are generated, so we might as well start the CLI where we expect it to end.

We should include the CLI arguments `--melodic-dimensionality` and `--error-on-warnings`, corresponding to the fMRIPrep arguments `--aroma-melodic-dimensionality` and `--error-on-aroma-warnings`.

**Comment by geowk** [comment]
Is fmipost-aroma available for use or is it still in the beginning stages of development?

thanks.

-g

**Comment by tsalo** [comment]
It's still in the beginning stages.

**Comment by tsalo** [comment]
Given #12, I believe the CLI will need two basic configurations. In the first scenario (the original one above), users have the raw dataset and fMRIPrep derivatives with at least minimal outputs.

```
fmripost-aroma <bids-dir> <out-dir> participant -d fmriprep=<fmriprep-dir> [OPTIONS]
```

In the second scenario, users have fMRIPrep derivatives with resampling or full outputs.

```
fmripost-aroma <fmriprep-dir> <out-dir> participant [OPTIONS]
```

**Comment by tsalo** [comment]
I think it works with either one right now.
