### ISSUE TITLE
No clear way to ignore known dummy frames for ICA-AROMA, etc...

### ISSUE THREAD

**Issue by alexlicohen** [nipreps/fmripost-aroma#13]
We are processing the GSP 1000 dataset, which does have dummy frames in the fMRI data, but we want to use the ICA-AROMA output. It would seem more logical to remove these frames up front before MELODIC is run. Informal comparison finds distinct differences in fcMaps between leaving them in vs truncating the file before fmriprep is run. What should be the appropriate sequence of steps here?

**Comment by tsalo** [comment]
This is now built into the fMRIPost-AROMA CLI.
