### ISSUE TITLE
Build on ReadTheDocs, add PR builds

### ISSUE THREAD

**Issue by effigies** [nipreps/fmripost-aroma#15]

**Comment by tsalo** [comment]
@effigies I think you need to enable the RTD build since I don't have the necessary nipreps permissions.

**Comment by effigies** [comment]
Can you add me as a maintainer on RTD?

**Comment by tsalo** [comment]
done!

**Comment by effigies** [comment]
Okay, should be enabled. Looks like we're missing some doc dependencies: https://beta.readthedocs.org/projects/fmripost-aroma/builds/24350750/

**Comment by tsalo** [comment]
I added the doc dependencies in #22 and it's now building, so I'll close this. Thanks for setting it up on RTD's end.
