### ISSUE TITLE
Generate reports

### ISSUE THREAD

**Issue by effigies** [nipreps/fmripost-aroma#3]
The reporting for fmripost-aroma should be relatively straightforward. The workflows copied in #2 should include boilerplate text that can be included as well as produce figures for inclusion in reports.

We will also want to shift to [nireports](https://github.com/nipreps/nireports/) for compiling the reports, while we're here. https://github.com/nipreps/mriqc/pull/1085 should be our model, though it will take some work to sift through that diff, since the reporting in MRIQC is pretty extensive. Our use should be much less so.

**Comment by tsalo** [comment]
I think this is handled now.
