### ISSUE TITLE
Release Docker builds failing

### ISSUE THREAD

**Issue by tsalo** [nipreps/fmripost-aroma#53]
There's a problem with the `docker/build-push-action` config.

Here's the error:

> ERROR: invalid tag "nipreps/fmripost-aroma:${{ steps.meta.outputs.tags }}": invalid reference format

**Comment by effigies** [comment]
https://docs.docker.com/build/ci/github-actions/manage-tags-labels/

**Comment by tsalo** [comment]
It's fixed as of #55!
