### ISSUE TITLE
Naming of html reports and aroma regressors

### ISSUE THREAD

**Issue by burdinskid13** [nipreps/fmripost-aroma#8]
### What would you like to see added in fMRIPrep?

html report naming:
For my use case, I need to run fmriprep on two sessions separately. i'd like to be able to merge the outputs into the same derivatives directory afterwards. however, since the html reports in the new layout (eg. in v22) are above the ses-* directory, i would need to rename the html reports in order to not have two files named the same in the same location. it would be great if the html report naming could include ses-* in addition to sub-*. 

ICA aroma regressor naming:
I noticed that the naming of ICA aroma regressors in *_desc-confounds_timeseries.json and *_desc-confounds_timeseries.tsv is inconsistent. Naming the two regressors the same would make workflows just a little smoother. For example, the first motion regressor in the json is called "aroma_motion_1" but in the tsv it's called " aroma_motion_01". i got this with v22.0.2. 

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance

**Comment by tsalo** [comment]
fMRIPost-AROMA has the `--aggregate-session-reports` parameter, so HTML reports are named appropriately now. We can make changes to the AROMA regressors if folks want, but I'm going to close this issue.
